dev/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.sitemaps.views import sitemap

# Call myroot properties
import myroot.views.vmain
import myroot.views.vdashboard

# Call SiteMap properties
from myroot.views.sitemap import (ContactUsSitemap, StaticViewSitemap)

sitemaps = {
    'contacts': ContactUsSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helloworld/', myroot.views.vmain.hello_world_view,
         name='helloworld'),

    path('django-basic-crud-create/',
         myroot.views.vmain.basic_crud_create_view,
         name='basic_crud_create'),

    path('django-basic-crud-list/',
         myroot.views.vmain.basic_crud_list_view,
         name='basic_crud_list'),

    path('django_basic_crud_delete/',
         myroot.views.vmain.basic_crud_del_row_view,
         name='basic_crud_delete'),

    path('<slug:slug>-<int:id>/',
         myroot.views.vmain.basic_crud_dynamic_public_page_view,
         name='basic_crud_dyn_pub_page'),

    path('basic_crud/<int:id>/change/', myroot.views.vmain.basic_crud_update_row_view,
         name='change_basic_crud'),

    path('basic_search_text/', myroot.views.vmain.basic_search_text_view,
         name='basic_search_text'),

    path('basic_search_dr/', myroot.views.vmain.basic_search_dr_view,
         name='basic_search_dr'),

    path('search/', myroot.views.vmain.search_view,
         name='search'),

    path('emptysearch/', myroot.views.vmain.emptysearch_view,
         name='emptysearch'),

    # Django Caching related links
    path('cache-django-basic-crud-list/',
         myroot.views.vmain.cache_basic_crud_list_view,
         name='cache_basic_crud_list'),

    path('cache_basic_crud/<int:id>/change/', myroot.views.vmain.cache_basic_crud_update_row_view,
         name='cache_change_basic_crud'),

    # Django Auth System related links
    path('login/', myroot.views.vmain.login_view, name='login'),
    path('logout/', myroot.views.vmain.logout_view, name='logout'),
    path('register/', myroot.views.vmain.register_view, name='register'),

    path('account_activation_sent/', myroot.views.vmain.account_activation_sent,
         name='account_activation_sent'),

    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         myroot.views.vmain.activate,
         name='activate'),

    path('password_reset/', myroot.views.vmain.password_reset_view,
         name='password_reset'),

    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         myroot.views.vmain.password_reset_confirm_view,
         name='password_reset_confirm'),

    path('reset_password_now/',
         myroot.views.vmain.reset_password_now_view,
         name='reset_password_now'),

    path('password_reset_done/', myroot.views.vmain.password_reset_done_view,
         name='password_reset_done'),

    path('reset/done/', myroot.views.vmain.password_reset_complete_view,
         name='password_reset_complete'),

    path('contactus_with_celery/', myroot.views.vmain.contactus_with_celery_view, name='contactus_with_celery'),
    path('contactus_without_celery/', myroot.views.vmain.contactus_without_celery_view, name='contactus_without_celery'),

    # Dashboard related urls
    path('dashboard/', myroot.views.vdashboard.dashboard_view, name='dashboard'),

    path('change_password/', myroot.views.vdashboard.change_password_view,
         name='change_password'),

    # Django auto generate sitemap.xml file
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

myroot/models.py
from django.conf import settings
from django.db import models


class ContactUs(models.Model):
    full_name = models.CharField(max_length=75)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=75)
    message = models.TextField()
    submitted = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    deleted_date = models.DateField(null=True, blank=True)
    deleted_by = models.PositiveIntegerField(default=0)

    class Meta:
        index_together = ["full_name", "is_deleted"]
        db_table = 'dev_contact_us'
        verbose_name = 'Contact Us'
        verbose_name_plural = 'Contact Us'


class SiteConfig(models.Model):
    property_name = models.CharField(max_length=75, unique=True)
    property_value = models.CharField(max_length=254, null=True, blank=True)
    property_desc = models.CharField(max_length=255, null=True, blank=True)

    SC_Default = 'APPSETTING'
    SC_Option = (
        ('APP_CONF', 'App Setting'),
        ('GENERAL_CONF', 'General Setting'),
        ('PROHIBITED_USER_NAME', 'Prohibited User Name'),
        ('PROHIBITED_USER_EMAIL', 'Prohibited User Email'),
        ('OTHERS', 'Other'),
    )

    property_group = models.CharField(max_length=75, choices=SC_Option,
                                      default=SC_Default)

    class Meta:
        index_together = ["property_group"]
        db_table = 'dev_site_config'
        verbose_name = 'Site Config'
        verbose_name_plural = 'Site Configs'

myroot/views/sitemap.py
from django.conf import settings
from django.contrib import sitemaps
from django.urls import reverse
from django.utils.text import slugify

# Call myroot properties
from myroot.models import ContactUs


class ContactUsSitemap(sitemaps.Sitemap):
    priority = 0.5
    changefreq = 'daily'
    protocol = "https"

    def items(self):
        contacts = ContactUs.objects.filter(is_deleted=False).order_by('-id')[:250]  # latest 250 new entries
        return contacts

    def lastmod(self, item):
        mod_date = item.submitted  # Actual datetime field
        return mod_date

    def location(self, item):
        url = '/' + slugify(item.full_name) + '-' + str(item.id)  # Actual URL of the individual page
        return url


class StaticViewSitemap(sitemaps.Sitemap):
    priority = 0.5
    changefreq = 'daily'
    protocol = "https"

    def items(self):
        return ['helloworld', 'basic_crud_create', 'basic_crud_list', 'register', 'password_reset', 'login']

    def location(self, item):
        return reverse(item)

myroot/views/vdashboard.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Django Auth System
from django.contrib.auth.models import User
import requests

# Call myroot properties
from myroot.forms.fmain import ChangePasswordForm
from myroot.views.vfunctions import (dict_alert_msg, is_password_valid)


@login_required
def dashboard_view(request):
    """Renders the dashboard page."""
    if request.method == "GET":

        # Set session for the main left side bar active menu
        request.session['active_sidebar_menu'] = "dashboard"

        return render(request, 'myroot/dashboard/index.html',
                      {
                          'title': 'Dashboard',
                          'meta_desc': 'Welcome to your dashboard',
                          'active_sidebar_menu': request.session['active_sidebar_menu']
                       })


@login_required
def change_password_view(request):
    """Renders the custom change password from the user's dashboard page."""
    if request.method == "GET":

        # Get user info
        current_user = request.user
        formChangePassword = ChangePasswordForm(current_user.username)

        # Set session for the main left side bar active menu
        request.session['active_sidebar_menu'] = "change_password"

        return render(request, 'myroot/account/change_password.html',
                      {
                          'title': 'Change Password',
                          'meta_desc': 'Change your password.',
                          'formChangePassword': formChangePassword,
                          'active_sidebar_menu': request.session['active_sidebar_menu']
                       })

    data = dict()
    if request.method == 'POST':
        new_password1 = request.POST.get('new_password1')
        new_password2 = request.POST.get('new_password2')

        # Get user info
        current_user = request.user

        is_pass_valid, msg, title = is_password_valid(new_password1, new_password2)

        if not is_pass_valid:
            # Return some json response back to user
            data = dict_alert_msg('False', title, msg, 'error')

        else:

            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GRECAP_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post(settings.GRECAP_VERIFY_URL, data=data)
            result = r.json()
            ''' End reCAPTCHA validation '''

            if result['success']:
                # Check first if email existed in our users data
                if User.objects.filter(username=current_user.username):

                    # Change the password now
                    u = User.objects.get(username=current_user.username)
                    u.set_password(new_password1)
                    u.save()

                    msg = """Your new password was successfully changed."""
                    data = dict_alert_msg('True', 'Password Changed',
                                          msg, 'success')
                else:

                    # The username submitted is not found in our users data
                    msg = """Oops, username not found, please try again."""
                    data = dict_alert_msg('False', 'Username Not Found!',
                                          msg, 'error')
            else:

                # Return some json response back to user
                msg = """Invalid reCAPTCHA, please try again."""
                data = dict_alert_msg('False', 'Oops, Error', msg, 'error')

        return JsonResponse(data)

myroot/views/vfunctions.py
from datetime import datetime, timedelta
import timeago
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.conf import settings
import re


def dict_alert_msg(form_is_valid, alert_title, alert_msg, alert_type):
    """
    Function to call internal alert message to the user with the required
    paramaters: form_is_valid[True/False all small letters for json format],
    alert_title='string', alert_msg='string',
    alert_type='success, error, warning, info'
    """
    data = {
        'form_is_valid': form_is_valid,
        'alert_title': alert_title,
        'alert_msg': alert_msg,
        'alert_type': alert_type
    }
    return data


def convert_to_local_datetime(dt_value):
    MY_DT_FORMAT = '%Y-%m-%d %H:%M:%S'
    dt = dt_value
    created_date_str = dt.strftime(MY_DT_FORMAT)  # convert to string
    created_date = dt.strptime(created_date_str, MY_DT_FORMAT)

    # timeago in python library to get user's local time
    now = datetime.now() + timedelta(seconds=60 * 3.4)
    event_date = timeago.format(created_date, now)

    return str(event_date)


def is_email_valid(email):
    try:
        validate_email(email)
    except ValidationError:
        return False
    return True


def is_password_valid(new_password1, new_password2):
    """
    To check if password is valid or not.
    """
    is_pass_valid = False
    msg, title = '', ''

    if new_password1 != new_password2:
        # Display error message
        msg = "Passwords do not match, please try again."
        title = 'Password Not Match'

    elif len(new_password1) < settings.MIN_PASS_LENGTH:
        # Display error message
        msg = "This password must contain at least " + str(settings.MIN_PASS_LENGTH) + " characters."
        title = 'Password Too Short'

    elif not re.findall('\d', new_password1):
        # Display error message
        msg = "The password must contain at least 1 digit from 0-9."
        title = 'Password No Number'

    elif not re.findall('[A-Z]', new_password1):
        # Display error message
        msg = "The password must contain at least 1 uppercase letter from A-Z."
        title = 'Password No Upper'

    elif not re.findall('[a-z]', new_password1):
        # Display error message
        msg = "The password must contain at least 1 lowercase letter from a-z."
        title = 'Password No Lower'

    else:
        is_pass_valid = True

    return is_pass_valid, msg, title


def is_username_valid(username):
    """
    To check if the username is valid or not.
    """
    is_user_name_valid = False
    msg, title = '', ''

    if not re.findall(r'^[\w.@+-]+\Z', username):
        # Display error message, only allow special characters @, ., +, -, and _.
        msg = "Enter a valid username. This value may contain only alphanumeric values and @/./+/-/_ characters."
        title = 'Invalid Username'
    else:
        is_user_name_valid = True

    return is_user_name_valid, msg, title

myroot/templates/myroot/basic_crud_create.html
{% extends "myroot/layout_home.html" %}
{% load static %}

{% block extra_styles_head %}
<link rel="stylesheet" href="{% static 'summernote/summernote-bs4.css' %}">
{% endblock %}

{% block page_sub_title %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{ title }}</h1>
        <p>
            Welcome to Django Basic CRUD which is to CREATE or INSERT a new row to MySQL Database table name <b>dev_contact_us</b>.
            Submit any sample data to test the Django Forms and how exactly it behaves.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="https://pinoylearnpython.com/basic-django-crud-using-ajax-json-and-jquery-monolithic-architecture/" role="button">Learn more »</a>
            <a class="btn btn-secondary btn-lg" href="https://dev.pinoylearnpython.com/django-basic-crud-list/" role="button">Back to Django Manage Table Rows »</a>
        </p>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-md-1">

                <form id="formContactUs" class="" method="POST">
                    {% csrf_token %}

                    <div class="form-label-group">
                        {{ form.full_name }}
                        <label for="id_full_name">Full Name</label>
                    </div>

                    <div class="form-label-group">
                        {{ form.email }}
                        <label for="id_email">Email</label>
                    </div>

                    <div class="form-label-group">
                        {{ form.subject }}
                        <label for="id_subject">Subject</label>
                    </div>

                    <div class="form-label-group">
                        {{ form.message }}
                    </div>
                </form>

                <div class="">
                    <button class="btn btn-lg btn-primary btn-block" onclick="saveForm();" id="btnContactUs">Submit your Inquiry</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/common/common.js' %}" defer></script>
<script src="{% static 'summernote/summernote-bs4.min.js' %}" defer></script>
<script src="{% static 'sweetalert/sweetalert.js' %}" defer></script>

<script defer>
    var BASE_URL = "{{ BASE_URL }}";
    var COMMON_ASSETS_URL = "{% static 'assets/images/' %}";

    function saveForm()
    {
        //Get the form instance
        var $form = $("#formContactUs");
        id_full_name = $("#id_full_name").val();
        id_email = $("#id_email").val();
        id_subject = $("#id_subject").val();
        id_message = $("#id_message").val();

        if (id_full_name === undefined || id_full_name === null || id_full_name ===""){
            swal("Full Name is Required!", "Please enter your full name", "error");
            $("#id_full_name").focus();
            return false;
        }

        if (id_email === undefined || id_email === null || id_email ===""){
            swal("Email is Required!", "Please enter your email", "error");
            $("#id_email").focus();
            return false;
        }

        if (id_subject === undefined || id_subject === null || id_subject ===""){
            swal("Subject is Required!", "Please enter your subject", "error");
            $("#id_subject").focus();
            return false;
        }

        if (id_message === undefined || id_message === null || id_message ===""){
            swal("Message is Required!", "Please enter your message", "error");
            $("#id_message").focus();
            return false;
        }

        $.ajax({
            method: "POST",
            url: BASE_URL+'django-basic-crud-create/',
            data: $form.serialize(),
            cache: false,
            dataType: "json",
            beforeSend: function(){
                //Start displaying button's working animation
                var loadingText = '<i class="fa fa-circle-o-notch fa-spin"></i> working...';
                if ($("#btnContactUs").html() !== loadingText) {
                    $("#btnContactUs").data('original-text', $("#btnContactUs").html());
                    $("#btnContactUs").html(loadingText);
                }
            },
            success: function(jResults)
            {
                $("#btnContactUs").html($("#btnContactUs").data('original-text')); //stop animation and switch back to original text

                if(jResults.alert_type =='success'){
                    swal(jResults.alert_title, jResults.alert_msg, jResults.alert_type);
                    $form[0].reset(); // reset form data
                    $("#id_message").summernote("reset");
                    $("#id_full_name").focus();
                }
                else {
                    var strErr = jResults.alert_msg + '';
                    strErr = strErr.split(",").pop();
                    swal(jResults.alert_title, strErr, jResults.alert_type);
                }
            }
        });
    }

    $(document).ready(function()
    {
        $('#id_message').summernote({
            placeholder: 'Type your message here.',
            tabsize: 2,
            height: 300
        });
    });
</script>
{% endblock %}

myroot/templates/myroot/basic_crud_update.html
{% extends "myroot/layout_home.html" %}
{% load static %}

{% block extra_styles_head %}
<link rel="stylesheet" href="{% static 'summernote/summernote-bs4.css' %}">
{% endblock %}

{% block page_sub_title %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{ title }}</h1>
        <p>
            Welcome to Django Basic CRUD which is to UPDATE an existing row to MySQL Database table name <b>dev_contact_us</b>.
            Modify the sample data to test the Django Forms and how exactly it behaves.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="https://pinoylearnpython.com/basic-django-crud-using-ajax-json-and-jquery-monolithic-architecture/" role="button">Learn more »</a>
            <a class="btn btn-secondary btn-lg" href="https://dev.pinoylearnpython.com/django-basic-crud-list/" role="button">Back to Django Manage Table Rows »</a>
        </p>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-md-1">

                <form id="formContactUs" class="" method="POST">
                    {% csrf_token %}

                    <div class="form-label-group">
                        {{ formEdit.full_name }}
                        <label for="id_full_name">Full Name</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.email }}
                        <label for="id_email">Email</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.subject }}
                        <label for="id_subject">Subject</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.message }}
                    </div>
                </form>

                <div class="">
                    <button class="btn btn-lg btn-primary btn-block" onclick="saveForm();" id="btnContactUs">Update</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/common/common.js' %}" defer></script>
<script src="{% static 'summernote/summernote-bs4.min.js' %}" defer></script>
<script src="{% static 'sweetalert/sweetalert.js' %}" defer></script>

<script defer>
    var BASE_URL = "{{ BASE_URL }}";
    var COMMON_ASSETS_URL = "{% static 'assets/images/' %}";

    function saveForm()
    {
        //Get the form instance
        var $form = $("#formContactUs");
        id_full_name = $("#id_full_name").val();
        id_email = $("#id_email").val();
        id_subject = $("#id_subject").val();
        id_message = $("#id_message").val();
        var id = "{{ id }}";

        if (id_full_name === undefined || id_full_name === null || id_full_name ===""){
            swal("Full Name is Required!", "Please enter your full name", "error");
            $("#id_full_name").focus();
            return false;
        }

        if (id_email === undefined || id_email === null || id_email ===""){
            swal("Email is Required!", "Please enter your email", "error");
            $("#id_email").focus();
            return false;
        }

        if (id_subject === undefined || id_subject === null || id_subject ===""){
            swal("Subject is Required!", "Please enter your subject", "error");
            $("#id_subject").focus();
            return false;
        }

        if (id_message === undefined || id_message === null || id_message ===""){
            swal("Message is Required!", "Please enter your message", "error");
            $("#id_message").focus();
            return false;
        }

        $.ajax({
            method: "POST",
            url: BASE_URL+'basic_crud/' + id + '/change/',
            data: $form.serialize() + '&id='+id,
            cache: false,
            dataType: "json",
            beforeSend: function(){
                //Start displaying button's working animation
                var loadingText = '<i class="fa fa-circle-o-notch fa-spin"></i> working...';
                if ($("#btnContactUs").html() !== loadingText) {
                    $("#btnContactUs").data('original-text', $("#btnContactUs").html());
                    $("#btnContactUs").html(loadingText);
                }
            },
            success: function(jResults)
            {
                $("#btnContactUs").html($("#btnContactUs").data('original-text')); //stop animation and switch back to original text

                if(jResults.alert_type =='success'){
                    swal(jResults.alert_title, jResults.alert_msg, jResults.alert_type);
                    $("#id_full_name").focus();
                }
                else {
                    var strErr = jResults.alert_msg + '';
                    strErr = strErr.split(",").pop();
                    swal(jResults.alert_title, strErr, jResults.alert_type);
                }
            }
        });
    }

    $(document).ready(function()
    {
        $('#id_message').summernote({
            placeholder: 'Type your message here.',
            tabsize: 2,
            height: 300
        });
    });
</script>
{% endblock %}

myroot/templates/myroot/basic_django_dynamic_public_page.html
{% extends "myroot/layout_home.html" %}
{% load static %}
{% load humanize %}

{% block extra_styles_head %}{% endblock %}

{% block page_sub_title %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Django Basic Dynamic Public Page</h1>
        <p>
            This is the dynamic public page as an example of how to fetch the database table row and load it accordingly.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="https://pinoylearnpython.com/basic-django-crud-using-ajax-json-and-jquery-monolithic-architecture/" role="button">Learn more »</a>
            <a class="btn btn-secondary btn-lg" href="https://dev.pinoylearnpython.com/django-basic-crud-list/" role="button">Back to Django Manage Table Rows »</a>
        </p>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-md-1">
                {% if db_data %}
                    {% for d in db_data %}
                        <h2 class="display-4 text-bold mt-0">{{ d.full_name }}</h2>
                        <p class="text-gray-soft lead">
                            <b>SUBJECT:</b> {{ d.subject }} <br/>
                            <b>EMAIL:</b> {{ d.email }} <br/>
                            <b>SUBMITTED:</b> {{ d.submitted|naturaltime }}
                        </p>
                        <p class="text-gray-soft lead">
                            <b>Long Content:</b> <br/>
                            {{ d.message|safe }}
                        </p>
                    {% endfor %}
                {% else %}
                    <p>Nothing to display table row.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}{% endblock %}

myroot/templates/myroot/cache_basic_crud_update.html
{% extends "myroot/layout_home.html" %}
{% load static %}

{% block extra_styles_head %}
<link rel="stylesheet" href="{% static 'summernote/summernote-bs4.css' %}">
{% endblock %}

{% block page_sub_title %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{ title }}</h1>
        <p>
            Welcome to Django Memcached with django-cache-memoize Basic CRUD which is to UPDATE an existing row to MySQL Database table name <b>dev_contact_us</b>.
            Modify the sample data to test the Django Forms and how exactly it behaves.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="https://pinoylearnpython.com/django-memcached-with-django-cache-memoize/" role="button">Learn more »</a>
            <a class="btn btn-secondary btn-lg" href="https://dev.pinoylearnpython.com/cache-django-basic-crud-list/" role="button">Back to Django Memcached Manage Table Rows »</a>
        </p>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-md-1">

                <form id="formContactUs" class="" method="POST">
                    {% csrf_token %}

                    <div class="form-label-group">
                        {{ formEdit.full_name }}
                        <label for="id_full_name">Full Name</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.email }}
                        <label for="id_email">Email</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.subject }}
                        <label for="id_subject">Subject</label>
                    </div>

                    <div class="form-label-group">
                        {{ formEdit.message }}
                    </div>
                </form>

                <div class="">
                    <button class="btn btn-lg btn-primary btn-block" onclick="saveForm();" id="btnContactUs">Update</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/common/common.js' %}" defer></script>
<script src="{% static 'summernote/summernote-bs4.min.js' %}" defer></script>
<script src="{% static 'sweetalert/sweetalert.js' %}" defer></script>

<script defer>
    var BASE_URL = "{{ BASE_URL }}";
    var COMMON_ASSETS_URL = "{% static 'assets/images/' %}";

    function saveForm()
    {
        //Get the form instance
        var $form = $("#formContactUs");
        id_full_name = $("#id_full_name").val();
        id_email = $("#id_email").val();
        id_subject = $("#id_subject").val();
        id_message = $("#id_message").val();
        var id = "{{ id }}";

        if (id_full_name === undefined || id_full_name === null || id_full_name ===""){
            swal("Full Name is Required!", "Please enter your full name", "error");
            $("#id_full_name").focus();
            return false;
        }

        if (id_email === undefined || id_email === null || id_email ===""){
            swal("Email is Required!", "Please enter your email", "error");
            $("#id_email").focus();
            return false;
        }

        if (id_subject === undefined || id_subject === null || id_subject ===""){
            swal("Subject is Required!", "Please enter your subject", "error");
            $("#id_subject").focus();
            return false;
        }

        if (id_message === undefined || id_message === null || id_message ===""){
            swal("Message is Required!", "Please enter your message", "error");
            $("#id_message").focus();
            return false;
        }

        $.ajax({
            method: "POST",
            url: BASE_URL+'cache_basic_crud/' + id + '/change/',
            data: $form.serialize() + '&id='+id,
            cache: false,
            dataType: "json",
            beforeSend: function(){
                //Start displaying button's working animation
                var loadingText = '<i class="fa fa-circle-o-notch fa-spin"></i> working...';
                if ($("#btnContactUs").html() !== loadingText) {
                    $("#btnContactUs").data('original-text', $("#btnContactUs").html());
                    $("#btnContactUs").html(loadingText);
                }
            },
            success: function(jResults)
            {
                $("#btnContactUs").html($("#btnContactUs").data('original-text')); //stop animation and switch back to original text

                if(jResults.alert_type =='success'){
                    swal(jResults.alert_title, jResults.alert_msg, jResults.alert_type);
                    $("#id_full_name").focus();
                }
                else {
                    var strErr = jResults.alert_msg + '';
                    strErr = strErr.split(",").pop();
                    swal(jResults.alert_title, strErr, jResults.alert_type);
                }
            }
        });
    }

    $(document).ready(function()
    {
        $('#id_message').summernote({
            placeholder: 'Type your message here.',
            tabsize: 2,
            height: 300
        });
    });
</script>
{% endblock %}